package com.java.movieticketingsystem.auth.helper;

import io.jsonwebtoken.Claims;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.SignatureAlgorithm;
import io.jsonwebtoken.io.Decoders;
import io.jsonwebtoken.security.Keys;
import lombok.Getter;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.stereotype.Component;

import java.security.Key;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.function.Function;

@Getter
@Component
public class JwtService {

    @Value("${jwt.secret}")
    private String secret;

    /**
     * Generate token with given username
     *
     * @param username The username i.e. email of the signing user.
     * @return The access token for the authenticated user.
     */
    public String generateToken(String username) {
        Map<String, Object> claims = new HashMap<>();
        return createToken(claims, username);
    }

    /**
     * Create a JWT token with specified claims and subject (email/username)
     *
     * @param claims The attributes of the user in the database
     * @param username The username i.e. email of the signing user.
     * @return The token generated by the jwt hashing algorithm.
     */
    private String createToken(Map<String, Object> claims, String username) {
        return Jwts.builder()
                .setClaims(claims)
                .setSubject(username)
                .setIssuedAt(new Date())
                .setExpiration(new Date(System.currentTimeMillis() + 1000 * 60 * 5)) // Token valid for 5 minutes
                .signWith(getSignKey(), SignatureAlgorithm.HS256)
                .compact();
    }

    /**
     * Get the signing key for JWT token
     *
     * @return The signing key
     */
    private Key getSignKey() {
        byte[] keyBytes = Decoders.BASE64.decode(getSecret());
        return Keys.hmacShaKeyFor(keyBytes);
    }

    /**
     * Extract the username from the token
     *
     * @param token The token supplied
     * @return The username i.e. email of the authenticated token.
     */
    public String extractUsername(String token) {
        return extractClaim(token, Claims::getSubject);
    }

    /**
     * Extract the expiration date from the token
     *
     * @param token The token supplied
     * @return The expiration date for the token.
     */
    public Date extractExpiration(String token) {
        return extractClaim(token, Claims::getExpiration);
    }

    /**
     * Extract a claim from the token
     *
     * @param token The token supplied
     * @param claimsResolver The claim resolver used to resolve claims.
     * @return The claim type resolved and its value.
     */
    public <T> T extractClaim(String token, Function<Claims, T> claimsResolver) {
        final Claims claims = extractAllClaims(token);
        return claimsResolver.apply(claims);
    }

    /**
     * Extract all claims from the token
     *
     * @param token The token supplied
     * @return The claims of authenticated user.
     */
    private Claims extractAllClaims(String token) {
        return Jwts.parserBuilder()
                .setSigningKey(getSignKey())
                .build()
                .parseClaimsJws(token)
                .getBody();
    }

    /**
     *  Checks if the token is expired
     *
     * @param token The token supplied
     * @return The flag indicating whether the token is expired or not.
     */
    private Boolean isTokenExpired(String token) {
        return extractExpiration(token).before(new Date());
    }

    /**
     * Validate the token against user details and expiration
     *
     * @param token The token supplied
     * @param userDetails The details of the user.
     * @return The flag indicating whether the token is valid or not.
     */
    public Boolean validateToken(String token, UserDetails userDetails) {
        final String username = extractUsername(token);
        return (username.equals(userDetails.getUsername()) && !isTokenExpired(token));
    }

    private String getSecret() {
        // Replace this with your actual secret retrieval logic
        return "aGVsbG9pYW1zb25hbTIwMDQ=";
    }

}
